version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules:cached

  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - 8080:8080

volumes:
  node_modules:
