name: "depcruise"
on:
  pull_request:

jobs:
  report:
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: MH4GF/dependency-cruiser-report-action@v2
